name: Integration
# This workflow is triggered on pushes to the repository. Testing!
on: [push]

jobs:
    build:
      # Job name is test-k2sc
      name: test-k2sc
      # This job runs on Linux
      runs-on: ubuntu-latest
      steps:
        - name: run-tests
          uses: actions/checkout@v1
          with: 
            python.version: '3.7'
          template: .workflow-template.yml
