name: Integration
# This workflow is triggered on pushes to the repository. Testing!
on: [push]

jobs:
    build:
      # Job name is test-k2sc
      name: test-k2sc
      # This job runs on Linux
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v1

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
          name: 'Use Python $(python.version)'

        - run:
            python -m pip install --upgrade pip setuptools wheel
            python setup.py install
          name: 'Install halophot & dependencies'

        - run: pytest --junitxml=junit/test-results.xml 
          name: 'Run pytest'